name    'guilhermef-nginx'
version '0.0.3'
source 'http://github.com/guilhermef/puppetlabs-nginx'
author 'Guilherme Souza'
license 'Apache License Version 2.0'
summary 'Puppet NGINX management module tornado friendly'
description 'This module can be used for basic NGINX Management'
project_page 'http://github.com/guilhermef/puppetlabs-nginx'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
